# Generated by Django 3.0.3 on 2020-02-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('sqft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Tech_enabled_room', models.BooleanField()),
                ('Private_Cabins', models.BooleanField()),
                ('Open_Workspaces', models.BooleanField()),
                ('Work_Anytime', models.BooleanField()),
                ('Game_Zone', models.BooleanField()),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
